Task-132
HelpLine-SPTech/helpline-front pull request #9
Opened 2024-05-22 14:35 UTC by nayrabelarmino

2024-05-22 14:41 UTC, Renan2805 commented
Troca a branch de destino pra develop invés de master

2024-05-22 14:42 UTC, Renan2805 requested changes
Troca a branch de destino pra develop invés da master

2024-05-23 20:50 UTC, Renan2805 requested changes

2024-05-23 20:50 UTC, Renan2805 commented on src/components/Institucional/NavBarInstitucional/NavBar.jsx
> +          <li className="nav-item"><a href="#" className="nav-link">ONGs</a></li>
Você precisa usar a tag `<Link />` ao invés de `<a />`, o equivalente disso seria `<Link to="#" className="nav-link"/> `

2024-05-23 20:50 UTC, Renan2805 commented on src/components/Institucional/NavBarOng/NavBarOng.jsx
Acho que invés de criar componentes diferentes da navbar para cada tipo de usuário, poderia usar condições para exibir ou não um link da navbar, por exemplo:

```
<header className="header font-poppins d-flex">
  <nav className="nav">
    <ul className="nav-list">
      <li className="nav-item"><a href="#" className="nav-link">Início</a></li>
      <li className="nav-item"><a href="#" className="nav-link">Chat</a></li>
      {
          user.type == "ONG"
              ? <li className="nav-item"><a href="#" className="nav-link">Dashboard</a></li>
              : <li className="nav-item"><a href="#" className="nav-link">Vagas</a></li>
      }
      <a className='logo' href="#"><img src={logo} alt="HelpLine" className="logo-img" /></a>
      <li className="nav-item"><a href="#" className="nav-link">Notificações</a></li>
      <li className="nav-item"><a href="#" className="nav-link">Meu Perfil</a></li>
      <li className="nav-item"><a href="#" className="nav-link">Sair</a></li>
    </ul>
  </nav>
</header>
```
    
nesse exemplo somente caso o tipo do usuario seja ong, a opção dashboard vai aparecer e somente caso o usuario não seja uma ong a opção vagas vai aparecer, pode usar essa forma para os outros links também

pra pegar as informações do usuario logado olha na tela de summary da dashboard, lá tem um exemplo de como fazer

2024-05-23 20:54 UTC, Renan2805 commented on src/routes.zip
que isso?

2024-05-23 20:58 UTC, Renan2805 commented on src/routes.js
> +          <Route path='/institucional'>
Muda pra isso aqui

`<Route path='/institucional'>
    <Route path='/institucional' element={<TelaHome/>}/>
    <Route path='/institucional/us' element={<TelaHelpline/>}/>
    <Route path='/institucional/volunteer' element={<TelaVoluntariado/>}/>
</Route>`

2024-05-25 17:10 UTC, nayrabelarmino commented on src/routes.zip
Vou apagar, subi sem querer.

2024-05-26 20:02 UTC, Renan2805 approved these changes

2024-05-27 20:45 UTC, nayrabelarmino commented on src/routes.js
> +          <Route path='/institucional'>
Atualizado!

2024-05-27 23:16 UTC, merged